### ISSUE TITLE
simple audio playback not working

### ISSUE THREAD

**Issue by neerajnagi** [chewi/freeswitch-rayo-config#1]
ahn is running successfully with mod_rayo. but simple playback is giving error 

Invalid file format [ssml] for
2013-08-29 18:51:03.914313 [ERR] switch_core_file.c:150 Invalid file format [ssml] for [<speak xmlns="http://www.w3.org/2001/10/synthesis" version="1.0" xml:lang="en-US">
  <audio src="/var/punchblock/record/welcome.mp3"/>
</speak>]!
2013-08-29 18:51:03.914313 [INFO] rayo_output_component.c:425 Failed to open ssml://<speak xmlns="http://www.w3.org/2001/10/synthesis" version="1.0" xml:lang="en-US">
  <audio src="/var/punchblock/record/welcome.mp3"/>

**Comment by chewi** [comment]
I think someone else mentioned this problem to me. I'm pretty sure the config worked for me as-is. Maybe something has changed. If there is something missing, it'll be something small. Note that I'm using adhearsion-asr, which isn't used by default yet. This may well make a difference but at the same time, I get the impression that it's not supposed to be required. Unfortunately my work has dragged me onto something else for the moment and I may not even get a chance to look at this again until next month but I'll try.

**Comment by chewi** [comment]
Ah, judging by IRC, it looks like you got this working? If it was the missing voice in ssml.conf.xml then you must have modified that file yourself and I did mention this problem in the README. ;)
